sudo: required
services:
  - docker

before_install:
  - docker build -t anwdutta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anwdutta/docker-react npm run test -- --coverage
  

